name: silent_payments
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  blockchain_utils: ^4.2.0
  crypto: ^3.0.3
  coinlib: ^3.0.1
  pointycastle: ^3.7.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  convert: ^3.0.0
  elliptic: ^0.3.11
