name: silent_payments
description: A pure Dart library for working with Bitcoin Silent Payments.
version: 0.1.0
repository: https://github.com/kent-3/silent_payments

environment:
  sdk: ^3.7.2

dependencies:
  coinlib: ^3.0.1
  pointycastle: ^3.7.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  convert: ^3.1.2
  crypto: ^3.0.6
  elliptic: ^0.3.11
