name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Cache libsecp256k1
        id: cache-libsecp
        uses: actions/cache@v3
        with:
          path: build/libsecp256k1.so
          key: ${{ runner.os }}-libsecp256k1-${{ hashFiles('pubspec.lock') }}

      - name: Build libsecp256k1 with coinlib
        if: steps.cache-libsecp.outputs.cache-hit != 'true'
        run: dart run coinlib:build_linux

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
